import {
  createSelector,
  createSlice,
  type PayloadAction,
} from "@reduxjs/toolkit";
import type { Todos, TodosFilter } from "./types/todos";
// import type { RootState } from "../../store/store";
import { customAlphabet } from "nanoid";

import { createAppAsyncThunk } from "../../withType";
import { client } from "../../api/client";

const nanoid = customAlphabet("1234567890abcdefghijklmnopqrstuvwxyz", 12);

export const fetchTodos = createAppAsyncThunk("todos/fetchTodos", async () => {
  const response = await client.get<Todos[]>("/fakeApi/todos");
  return response.data;
});

interface TodoState {
  todos: Todos[];
  status: "idle" | "pending" | "succeeded" | "rejected";
  error: string | null;
  filter: TodosFilter;
}

const initialState: TodoState = {
  todos: [],
  status: "idle",
  error: null,
  filter: "all",
};

export const todoSlice = createSlice({
  name: "todos",
  initialState,
  reducers: {
    // addTodos: (state, action: PayloadAction<Todos>) => {
    //   // state.todos.push(action.payload);
    //   state.todos = [...state.todos, action.payload];
    // },
    addTodos: {
      // should actually be better named as todosAdded i.e. "past-tense"
      reducer(state, action: PayloadAction<Todos>) {
        state.todos = [...state.todos, action.payload];
      },
      prepare(name: string, description: string) {
        return {
          payload: {
            id: nanoid(),
            name,
            description,
            status: "todo" as Todos["status"],
          },
        };
      },
    },
    setFilter: (state, action: PayloadAction<TodosFilter>) => {
      state.filter = action.payload;
    },
  },
  extraReducers: (builder) => {
    builder
      .addCase(fetchTodos.pending, (state) => {
        state.status = "pending";
      })
      .addCase(fetchTodos.fulfilled, (state, action) => {
        state.status = "succeeded";
        state.todos = [...action.payload];
      })
      .addCase(fetchTodos.rejected, (state, action) => {
        state.status = "rejected";
        state.error = action.error.message ?? "Unknown Error";
      });
  },
  // // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // // including actions generated by createAsyncThunk or in other slices.
  // extraReducers: builder => {
  //   builder
  //     // Handle the action types defined by the `incrementAsync` thunk defined below.
  //     // This lets the slice reducer update the state with request status and results.
  //     .addCase(incrementAsync.pending, state => {
  //       state.status = 'loading'
  //     })
  //     .addCase(incrementAsync.fulfilled, (state, action) => {
  //       state.status = 'idle'
  //       state.value += action.payload
  //     })
  //     .addCase(incrementAsync.rejected, state => {
  //       state.status = 'failed'
  //     })
  // }
  selectors: {
    selectTodos: (todosState) => todosState.todos,
    selectTodosFilter: (todosState) => todosState.filter,
    selectTodosById: (todosState, todoId: string) => {
      return todosState.todos.find((todo) => todo.id === todoId);
    },
    selectTodosStatus: (todosState) => todosState.status,
  },
});

// // Thunks are commonly used for async logic like fetching data.
// // The `createAsyncThunk` method is used to generate thunks that
// // dispatch pending/fulfilled/rejected actions based on a promise.
// // In this example, we make a mock async request and return the result.
// // The `createSlice.extraReducers` field can handle these actions
// // and update the state with the results.
// export const incrementAsync = createAsyncThunk(
//   'counter/fetchCount',
//   async (amount: number) => {
//     const response = await fetchCount(amount)
//     // The value we return becomes the `fulfilled` action payload
//     return response.data
//   }
// )

export const { addTodos, setFilter } = todoSlice.actions;
export const {
  selectTodos,
  selectTodosFilter,
  selectTodosById,
  selectTodosStatus,
} = todoSlice.selectors;

// Memoized: only recomputes when `todos` or `filter` change.
export const selectFilteredTodos = createSelector(
  [selectTodos, selectTodosFilter],
  (todos, filter) =>
    filter === "all" ? todos : todos.filter((todo) => todo.status === filter),
);

// export const selectTodos = (state: RootState) => state.todos.todos;
// export const selectTodosFilter = (state: RootState) => state.todos.filter;
// export const selectTodosById = (state: RootState, todoId: string) =>
//   state.todos.todos.find((todo) => todo.id === todoId);

export default todoSlice.reducer;
